# Generated by Django 4.0 on 2022-02-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_message_date_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_read',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
