# Generated by Django 4.0 on 2021-12-26 08:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_project_vote_ratio_project_vote_total_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b6a2831f-a75f-40a7-8782-df6aae0d403d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.UUID('91fd2d54-c14b-4f10-bc0c-a4825265ebe5'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f3016005-638e-4c59-b570-4cdd0968667c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
