# Generated by Django 4.0 on 2021-12-29 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='souce_link',
            new_name='source_link',
        ),
    ]
